// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfuyqkcbpkrcragnytdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmdXlxa2NicGtyY3JhZ255dGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTUzODcsImV4cCI6MjA2NDEzMTM4N30.HPvTNWts0sVj3FD5WpvbASuLKbCYZNGzO29vzAC8XWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);